### ISSUE TITLE
Connection slow after restart

### ISSUE THREAD

**Issue by cdaerr** [iobroker-community-adapters/ioBroker.openknx#419] opened 2023-11-11 10:57 UTC
After restart of the host computer the connection to KNX interface seems to be "slow". Messeages are sent with delay to the KNX bus.
I tried to turn on and off a light (Licht Essen Schrank):

![grafik](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/98185044/1928a2d3-c58e-4d7a-ab27-0788dfe21e57)

When looking to ETS I saw that the command was send with delay of several seconds.
After restart of instance everything went fine again.

**To Reproduce**  
1. Restart host system
2. Send command to KNX actor
3. Reaction is delayed

**Versions:**  
 - Adapter version: 0.5.3
 - JS-Controller version: 5.0.12
- Node version: v16.20.2
- Operating system: linux

**Comment by cdaerr** [comment] 2023-11-11 12:37
After last restart (reason was an image backup) I got the following errors:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/98185044/fd2ea2b9-f521-42fd-a9d4-2df8ad281be0)

And after restarting the instance it works well

**Comment by boellner** [comment] 2023-12-02 22:51
after reset the adapter fetches a lot of ga values to be in sync. You can disable the feature, slow it down in the settings or disable it per ga. 
Does this explain your behavior?

**Comment by xmace** [comment] 2023-12-12 10:57
Same here! Issue is reproducable 
After importing new xml the adapter restarts and requests a lot of values but this is not the issue.
The delay with the above mentionen warnings still exist after 1h until you manually just restart the adapter.

If necessary, remote meeting is possible.

**Comment by cdaerr** [comment] 2023-12-13 10:56
The autoread of objects after startup is necessary to fetch up changes on KNX during iobroker/Adapter off time. I think this is necessary.
And I don't think that this is the problem, because the fetch of ga values does not get in trouble every time. Mostly it happens at reboot of the complete host. If I restart the KNX Adapter again after the other adapters are working, it seems to have less problems with the fetching.

**Comment by boellner** [comment] 2023-12-18 14:37
-Is it always the same GA that causes the issue?
-How is the IOB object json of that GA looking like?

Workaround could be to delete the whole object tree and do a fresh import.
In order to understand the problem, could you provide me some of your data
-either your complete object tree
-or nail it down by deleting unrelated objects, check if the error persists and give me an extract of this

**Comment by cdaerr** [comment] 2023-12-24 10:37
I don't think that is caused by a special GA. For me it looks like a connection issue.

Last week I updated the adapter to v0.6.3. It seems that the behavoir has changed:
The new busload objects stays at 0% when the issue occures.
A reset of the adapter seems to be unsufficient for successful reconnection. It has to be paused for some minutes, than a new connection is successful.

Is it possible that the adapter has problems reconnecting to the same tunneling channel?

Providing more detaild information is possible, but not over a public forum.

**Comment by boellner** [comment] 2023-12-28 21:03
please send a mail to boellnerboellner@gmail.com

**Comment by boellner** [comment] 2024-01-08 22:30
In what environment do you run iobroker? Can you please change logging mode to at least debug and report output here?
I cannot reproduce the issue on linux server pc and raspberry. I can reproduce a similar behavior when halting the applcation for long time in my docker environment.
-> I'm adding more info log messages in case of connection problems
-> I'm going to add some stability fixes in to the socket connection sections

**Comment by cdaerr** [comment] 2024-03-17 20:09
After update to 0.7.2, I had much error messages:

![jHejFU7TsuQCsPWF](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/98185044/e4a9213b-971f-48ee-b39c-cb31f6cb519f)

Only stop instance for short time and start again solved the problem.

**Comment by boellner** [comment] 2024-03-30 00:01
fixed with this pr https://github.com/iobroker-community-adapters/ioBroker.openknx/pull/459

**Closed** 2024-04-20 14:41 UTC
Labels: under investigation, fixed

**Comment by cdaerr** [comment] 2024-06-27 11:07
The issue occured with 0.9.0 again.
After restart a hugh delay of several seconds occured when sending commands to KNX. An Adapter restart was needed to get good behaviour.
