### ISSUE TITLE
Switch to KNXEngine from node knx ultimate

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#101] opened 2022-01-17 11:15 UTC
Less bugs, more DPs and future proof

**Comment by boellner** [comment] 2022-01-17 21:39
evaluation is done earliest when the knx secure feature is introduces, as discussed in #59

**Comment by TA2k** [comment] 2022-01-17 22:01
KNX Secure is not important why wait for this

**Comment by boellner** [comment] 2022-01-18 22:26
duplicate of #59

**Comment by TA2k** [comment] 2022-01-19 15:09
No this is about knx secure which will not come this year in the knx engine
this is about to use the bugfixed, improvments and new dpt type from knx engine.
Please switch to the better engine

**Comment by TA2k** [comment] 2022-01-20 08:21
When is it planned to integrate the missing DPT which KNX Engine provides?

**Comment by boellner** [comment] 2022-01-21 20:47
as soon as this library offers knx secure

**Comment by TA2k** [comment] 2022-01-21 22:11
It looks like this will not happen this year.
Why fixing bugs twice 
This means waiting 1 year for DPT > 238 and UDP error bugfix?

**Comment by boellner** [comment] 2022-01-22 20:05
it is ready by mid 2022.

**Comment by TA2k** [comment] 2022-01-22 21:09
The project is searching for help to implement knx secure I don't see this feature coming 2022. 
The feature request is not about useless KNX Secure its about bugfixes and already available features.
Please provide arguments why not adapting this now, closing tickets doesn't help here.

**Comment by TA2k** [comment] 2022-01-23 18:17
Can you please provide arguments before closing. Is the main argument you personal wont migrate before knx secure. Please allow other community member to migrate before mid 2022

**Comment by boellner** [comment] 2022-01-23 19:14
duplicate issue, as explained before

**Comment by TA2k** [comment] 2022-01-23 20:01
Are other community members allowed to migrate or only you?

**Comment by boellner** [comment] 2022-01-26 22:21
this is becoming a hypothetical discussion, you got my timeline. we can close this parallel discussion

**Comment by TA2k** [comment] 2022-06-05 21:23
It is mid 2022 are we now allowed to switch to KNX ultimate.
This library includes a lot more DPT and all the ACK fixes wich are manually added to knx lib

**Comment by TA2k** [comment] 2023-01-23 10:07
This mean no switch to knx ultimate is planned. 
To use the the maintained KNX ultimate instead of the outdated knx.js it needs a new alternative adapter?

**Closed** 2023-03-10 21:56 UTC
